[package]
name = "server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3"
env_logger = "0.9"
log = "0.4"
tera = "1.15"
glob = "0.3"
serde = "1.0"
toml = "0.5"